[versions]
aoc-kotlin = "1.1.2"
arrow = "2.2.1.1"
flexmark = "0.64.8"
kaliningraph = "0.2.1"
kotlin = "2.3.0"
kotlinx-benchmark = "0.4.15"
kotlin-logging = "7.0.13"
krid = "0.0.2-SNAPSHOT"
jgrapht = "1.5.2"
junit = "6.0.1"
assertj = "3.27.6"
spring-boot = "4.0.1"
timefold = "1.29.0"
logback = "1.5.22"
kotlin-graphs = "0.6.1"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }

kotlinx-benchmark = { id = "org.jetbrains.kotlinx.benchmark", version.ref = "kotlinx-benchmark" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.7" }

[libraries]
aoc-kotlin = { group = "com.toldoven.aoc", name = "aoc-kotlin-notebook", version.ref = "aoc-kotlin" }
arrow-core = { group = "io.arrow-kt", name = "arrow-core", version.ref = "arrow" }
arrow-functions = { group = "io.arrow-kt", name = "arrow-functions", version.ref = "arrow" }
arrow-fx-coroutines = { group = "io.arrow-kt", name = "arrow-fx-coroutines", version.ref = "arrow" }

flexmark-html2md-converter = { group = "com.vladsch.flexmark", name = "flexmark-html2md-converter", version.ref = "flexmark" }

jgrapht-core = { group = "org.jgrapht", name = "jgrapht-core", version.ref = "jgrapht" }
kaliningraph = { group = "ai.hypergraph", name = "kaliningraph-jvm", version.ref = "kaliningraph" }
kotlin-graphs = { group = "io.github.alexandrepiveteau", name = "kotlin-graphs", version.ref = "kotlin-graphs" }

kotlinx-benchmark-runtime = { group = "org.jetbrains.kotlinx", name = "kotlinx-benchmark-runtime", version.ref = "kotlinx-benchmark" }
krid = { group = "io.toolisticon.lib", name = "krid", version.ref = "krid" }

junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit" }


kotlin-logging = { group = "io.github.oshai", name = "kotlin-logging-jvm", version.ref = "kotlin-logging" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }

spring-boot-starter-web = { group = "org.springframework.boot", name = "spring-boot-starter-web", version.ref = "spring-boot" }
spring-boot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test", version.ref = "spring-boot" }
spring-boot-dependencies = { group = "org.springframework.boot", name = "spring-boot-dependencies", version.ref = "spring-boot" }
springdoc-starter-ui = { group = "org.springdoc", name = "springdoc-openapi-starter-webmvc-ui", version = "3.0.0" }

timefold-solver-core = { group = "ai.timefold.solver", name = "timefold-solver-core", version.ref = "timefold" }
timefold-solver-test = { group = "ai.timefold.solver", name = "timefold-solver-test", version.ref = "timefold" }

assertj-core = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }
